global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-metrics'
    static_configs:
      # Notice we use the service name from docker-compose, not localhost!
      - targets: ['depression-api:8000']